### ISSUE TITLE
The following resource(s) failed to create: [ScheduledServiceIAMRole]

### ISSUE THREAD

**Issue by AdvikEshan** [awslabs/amazon-redshift-monitoring#26]
The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument
![image](https://user-images.githubusercontent.com/23567081/86558764-e4459400-bf77-11ea-96ab-d9b62b6cb487.png)

I have given **AdministratorAccess** permission to the role which I am using to run the CloudFormation template.

**Comment by IanMeyers** [comment]
Looking into this.

**Comment by IanMeyers** [comment]
My guess is that you supplied a null/empty KmsKeyARN parameter. Is that correct? This is required and cannot be blank, as it's required to grant decrypt rights on the password.

**Comment by IanMeyers** [comment]
Please disregard the above - can now reproduce the issue. Will come back to you.

**Comment by IanMeyers** [comment]
There were several bugs introduced to the deployment cloudformation templates. Please try again with the updated versions and let me know?

**Comment by AdvikEshan** [comment]
Thank you so much @IanMeyers for looking into it. I'll try this again and will let you know.

**Comment by AdvikEshan** [comment]
@IanMeyers It's working now. Thank you!
