### ISSUE TITLE
Password decrypt is timing out

### ISSUE THREAD

**Issue by saunakc** [awslabs/amazon-redshift-monitoring#3]
I have setup the KMS key in the same region where the Redshift cluster resides. Encrypted the database user password using command line "aws kms encrypt --key-id $KEY_ID --plaintext <password>". Edited the lambda_function.py script to fill in the configurations where the enc_password field is set to the "CiphertextBlob" output from the above command line. Now when I am running a test on the lambda function the decrypt step is timing out. Any suggestion on why it is timing out would be appreciated.

**Comment by javierros** [comment]
Are you running the Lambda function in a VPC?, if so, then you should run the Lambda function in a private subnet, and configure the routing table to use a NAT Gateway in a public subnet to access Intenet (http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html)
