### ISSUE TITLE
no new metrics after 3 days?

### ISSUE THREAD

**Issue by t-readyroc** [awslabs/amazon-redshift-monitoring#5]
Hi again - I've got the function successfully running hourly, but I don't see any new metrics resulting from it.  Here's an error reported in the logs that might be related:

> (u'ERROR', u'42P01', u'relation "sensor_data" does not exist', u'/home/ec2-user/padb/src/pg/src/backend/catalog/namespace.c', u'237', u'RangeVarGetRelid'): ProgrammingError
> Traceback (most recent call last):
> File "/var/task/lambda_function.py", line 328, in lambda_handler
put_metrics.extend(run_external_commands('User Configured', 'user-queries.json', cursor, cluster))
> File "/var/task/lambda_function.py", line 93, in run_external_commands
interval = run_command(cursor, command['query'])
> File "/var/task/lambda_function.py", line 129, in run_command
cursor.execute(statement)
> File "/var/task/lib/pg8000/core.py", line 852, in execute
self._c.execute(self, operation, args)
> File "/var/task/lib/pg8000/core.py", line 1741, in execute
self.handle_messages(cursor)
> File "/var/task/lib/pg8000/core.py", line 1879, in handle_messages
raise self.error
> ProgrammingError: (u'ERROR', u'42P01', u'relation "sensor_data" does not exist', u'/home/ec2-user/padb/src/pg/src/backend/catalog/namespace.c', u'237', u'RangeVarGetRelid')

This error is reported at least twice for each Lambda run, amongst the series of diagnostic queries.  Here's a [screenshot](https://i.imgur.com/6rK5hvG.png).  I do not see any new metrics for Redshift listed.

**Comment by t-readyroc** [comment]
Fixed/worked around. Removed the example query from user-queries.json, and the function executed successfully. I'd suggest a caveat in the documentation to avoid confusion. I've got a branch with an updated README if you'd like to check it out.

**Comment by IanMeyers** [comment]
Added a try:catch for external commands, and updated readme.
