### ISSUE TITLE
link for VPC stack for us -east1 

### ISSUE THREAD

**Issue by Anuj79** [awslabs/amazon-redshift-monitoring#7]
the URL for east-1 is incorrect so cant Launch the stack has changed..it 
https://s3-us-east-1.amazonaws.com/awslabs-code-us-east-1/RedshiftAdvancedMonitoring/deploy-vpc.yaml

it should be 
https://s3.amazonaws.com/awslabs-code-us-east-1/RedshiftAdvancedMonitoring/deploy-vpc.yaml

**Comment by IanMeyers** [comment]
This is now fixed.
